# Name of the workflow
name: First Workflow

# When the workflow will be triggered
on: workflow_dispatch

# The work that needs to be completed with the workflow
jobs: 
  # Give your job a name, can be anything you want. 
  first-job: 
    #Identify the runner - Google "Github Actions Runners" for a complete list of potential runners
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        #Steps can either be CLI Commands or "Actions"
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"

# Note: In order to run multiple shell cmds in one step, you would use the <|> symbol, example below.  
#    run: |
#     echo "First output"
#     echo "Second output"
